"""encrypt_summary_and_user_attributes

Revision ID: 03400aafd4e5
Revises: 8c4f5a9b2e10
Create Date: 2026-06-22 10:50:48.280328

"""
from __future__ import annotations

import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.encryption import FieldEncryption


# revision identifiers, used by Alembic.
revision: str = '03400aafd4e5'
down_revision: Union[str, None] = '8c4f5a9b2e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _encrypt_existing_reports(conn: sa.engine.Connection) -> None:
    """将 reports 表中现有的 summary 与 attributes 加密存储."""
    rows = conn.execute(
        sa.text(
            "SELECT id, summary, attributes FROM reports "
            "WHERE summary IS NOT NULL OR attributes IS NOT NULL"
        )
    )
    for row_id, summary, attributes in rows:
        new_summary = FieldEncryption.encrypt(summary) if summary else None
        new_attributes = FieldEncryption.encrypt(json.loads(attributes)) if attributes else None
        conn.execute(
            sa.text(
                "UPDATE reports SET summary = :summary, attributes = :attributes WHERE id = :id"
            ),
            {"summary": new_summary, "attributes": new_attributes, "id": row_id},
        )


def _encrypt_existing_users(conn: sa.engine.Connection) -> None:
    """将 users 表中现有的 attributes 加密存储."""
    rows = conn.execute(
        sa.text("SELECT id, attributes FROM users WHERE attributes IS NOT NULL")
    )
    for row_id, attributes in rows:
        new_attributes = FieldEncryption.encrypt(json.loads(attributes))
        conn.execute(
            sa.text("UPDATE users SET attributes = :attributes WHERE id = :id"),
            {"attributes": new_attributes, "id": row_id},
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_reflections',
    sa.Column('tenant_id', sa.String(length=36), nullable=True, comment='租户 ID'),
    sa.Column('task_name', sa.String(length=128), nullable=True, comment='任务名称'),
    sa.Column('task_id', sa.String(length=64), nullable=True, comment='任务 ID'),
    sa.Column('resource_type', sa.String(length=64), nullable=True, comment='资源类型'),
    sa.Column('resource_id', sa.String(length=36), nullable=True, comment='资源 ID'),
    sa.Column('exception_type', sa.String(length=128), nullable=False, comment='异常类型'),
    sa.Column('exception_message', sa.Text(), nullable=False, comment='异常消息'),
    sa.Column('stack_trace', sa.Text(), nullable=True, comment='堆栈信息'),
    sa.Column('error_category', sa.String(length=32), nullable=False, comment='错误分类'),
    sa.Column('root_cause', sa.Text(), nullable=True, comment='根因分析'),
    sa.Column('suggested_fix', sa.Text(), nullable=True, comment='修复建议'),
    sa.Column('retried', sa.Boolean(), nullable=False, comment='是否已重试'),
    sa.Column('resolved', sa.Boolean(), nullable=False, comment='是否已解决'),
    sa.Column('resolution', sa.Text(), nullable=True, comment='解决方案'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_reflections_error_category'), 'error_reflections', ['error_category'], unique=False)
    op.create_index(op.f('ix_error_reflections_exception_type'), 'error_reflections', ['exception_type'], unique=False)
    op.create_index(op.f('ix_error_reflections_resource_id'), 'error_reflections', ['resource_id'], unique=False)
    op.create_index(op.f('ix_error_reflections_resource_type'), 'error_reflections', ['resource_type'], unique=False)
    op.create_index(op.f('ix_error_reflections_task_id'), 'error_reflections', ['task_id'], unique=False)
    op.create_index(op.f('ix_error_reflections_task_name'), 'error_reflections', ['task_name'], unique=False)
    op.create_index(op.f('ix_error_reflections_tenant_id'), 'error_reflections', ['tenant_id'], unique=False)
    op.drop_column('reports', 'encrypted_summary')
    # ### end Alembic commands ###

    # 迁移现有敏感数据为加密存储（需要 SECRET_KEY 环境变量）
    conn = op.get_bind()
    _encrypt_existing_reports(conn)
    _encrypt_existing_users(conn)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('encrypted_summary', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_error_reflections_tenant_id'), table_name='error_reflections')
    op.drop_index(op.f('ix_error_reflections_task_name'), table_name='error_reflections')
    op.drop_index(op.f('ix_error_reflections_task_id'), table_name='error_reflections')
    op.drop_index(op.f('ix_error_reflections_resource_type'), table_name='error_reflections')
    op.drop_index(op.f('ix_error_reflections_resource_id'), table_name='error_reflections')
    op.drop_index(op.f('ix_error_reflections_exception_type'), table_name='error_reflections')
    op.drop_index(op.f('ix_error_reflections_error_category'), table_name='error_reflections')
    op.drop_table('error_reflections')
    # ### end Alembic commands ###
