"""add_im_user_mapping

Revision ID: 2d052032bfd7
Revises: 81fb23289cf0
Create Date: 2026-06-19 04:10:12.407252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d052032bfd7'
down_revision: Union[str, None] = '81fb23289cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('im_user_mappings',
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='所属租户'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='系统用户 ID'),
    sa.Column('platform', sa.String(length=32), nullable=False, comment='IM 平台，如 dingtalk / feishu / wecom'),
    sa.Column('im_user_id', sa.String(length=128), nullable=False, comment='IM 平台用户唯一标识'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'platform', 'im_user_id', name='uq_tenant_platform_im_user')
    )
    op.create_index(op.f('ix_im_user_mappings_im_user_id'), 'im_user_mappings', ['im_user_id'], unique=False)
    op.create_index(op.f('ix_im_user_mappings_platform'), 'im_user_mappings', ['platform'], unique=False)
    op.create_index(op.f('ix_im_user_mappings_tenant_id'), 'im_user_mappings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_im_user_mappings_user_id'), 'im_user_mappings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_im_user_mappings_user_id'), table_name='im_user_mappings')
    op.drop_index(op.f('ix_im_user_mappings_tenant_id'), table_name='im_user_mappings')
    op.drop_index(op.f('ix_im_user_mappings_platform'), table_name='im_user_mappings')
    op.drop_index(op.f('ix_im_user_mappings_im_user_id'), table_name='im_user_mappings')
    op.drop_table('im_user_mappings')
    # ### end Alembic commands ###
