"""add_abac_and_field_encryption

Revision ID: 81fb23289cf0
Revises: fcec2006310a
Create Date: 2026-06-18 19:19:50.029580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81fb23289cf0'
down_revision: Union[str, None] = 'fcec2006310a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_policies',
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='租户 ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='策略名称'),
    sa.Column('resource_type', sa.String(length=64), nullable=False, comment='资源类型，如 report/document/query'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='操作，如 read/create/update/delete/approve'),
    sa.Column('effect', sa.String(length=16), nullable=False, comment='allow 或 deny'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级，数值越小优先级越高'),
    sa.Column('conditions', sa.JSON(), nullable=True, comment="策略条件，如 {'user.department': 'eq:finance'}"),
    sa.Column('description', sa.Text(), nullable=True, comment='策略描述'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_policies_action'), 'access_policies', ['action'], unique=False)
    op.create_index(op.f('ix_access_policies_resource_type'), 'access_policies', ['resource_type'], unique=False)
    op.create_index(op.f('ix_access_policies_tenant_id'), 'access_policies', ['tenant_id'], unique=False)
    op.add_column('reports', sa.Column('attributes', sa.JSON(), nullable=True, comment="ABAC 资源属性，如 {'sensitivity': 2, 'department': 'finance'}"))
    op.add_column('reports', sa.Column('encrypted_summary', sa.Text(), nullable=True, comment='加密存储的报告摘要（敏感内容）'))
    op.add_column('users', sa.Column('attributes', sa.JSON(), nullable=True, comment="ABAC 用户属性，如 {'department': 'finance', 'level': 3}"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'attributes')
    op.drop_column('reports', 'encrypted_summary')
    op.drop_column('reports', 'attributes')
    op.drop_index(op.f('ix_access_policies_tenant_id'), table_name='access_policies')
    op.drop_index(op.f('ix_access_policies_resource_type'), table_name='access_policies')
    op.drop_index(op.f('ix_access_policies_action'), table_name='access_policies')
    op.drop_table('access_policies')
    # ### end Alembic commands ###
