"""initial schema

Revision ID: d04c33d13d30
Revises:
Create Date: 2026-06-18 15:15:55.556694

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd04c33d13d30'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('tenant_id', sa.String(length=36), nullable=True, comment='租户 ID'),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='用户 ID'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='操作类型'),
    sa.Column('resource', sa.String(length=512), nullable=False, comment='资源标识'),
    sa.Column('input_hash', sa.String(length=64), nullable=True, comment='输入 SHA256'),
    sa.Column('output_hash', sa.String(length=64), nullable=True, comment='输出 SHA256'),
    sa.Column('model_version', sa.String(length=64), nullable=True, comment='模型版本'),
    sa.Column('ip', sa.String(length=64), nullable=True, comment='IP 地址'),
    sa.Column('result', sa.String(length=16), nullable=False, comment='结果: success/fail'),
    sa.Column('reason', sa.Text(), nullable=True, comment='失败原因'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=128), nullable=False, comment='租户名称'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='租户编码'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.create_table('financial_reports',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False, comment='Q1/Q2/Q3/Q4/H1/H2/annual'),
    sa.Column('report_type', sa.String(length=32), nullable=True, comment='报表类型'),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('operating_cost', sa.Float(), nullable=True),
    sa.Column('operating_profit', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('owner_equity', sa.Float(), nullable=True),
    sa.Column('cash_flow_operating', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_reports_period'), 'financial_reports', ['period'], unique=False)
    op.create_index(op.f('ix_financial_reports_tenant_id'), 'financial_reports', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_financial_reports_year'), 'financial_reports', ['year'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.String(length=36), nullable=False, comment='所属租户'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=128), nullable=True, comment='邮箱'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('role', sa.String(length=32), nullable=False, comment='角色'),
    sa.Column('is_active', sa.String(length=1), nullable=False, comment='是否启用'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_tenant_username')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('documents',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('storage_key', sa.String(length=512), nullable=False, comment='对象存储 key'),
    sa.Column('file_size', sa.String(length=32), nullable=True, comment='文件大小（字节）'),
    sa.Column('mime_type', sa.String(length=64), nullable=True, comment='文件类型'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态: pending/processing/success/failed'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='解析置信度'),
    sa.Column('parse_result', sa.JSON(), nullable=True, comment='解析结果（结构化数据）'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('reports',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False, comment='报告标题'),
    sa.Column('report_type', sa.String(length=64), nullable=False, comment='报告类型: profit/balance/cash/custom'),
    sa.Column('parameters', sa.JSON(), nullable=False, comment='报告参数'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='状态: draft/pending/reviewing/approved/rejected/published'),
    sa.Column('content', sa.JSON(), nullable=True, comment='报告内容（JSON）'),
    sa.Column('content_url', sa.String(length=512), nullable=True, comment='导出文件存储地址'),
    sa.Column('summary', sa.Text(), nullable=True, comment='报告摘要'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_tenant_id'), 'reports', ['tenant_id'], unique=False)
    op.create_table('approvals',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False, comment='操作: submit/approve/reject/modify'),
    sa.Column('comments', sa.Text(), nullable=True, comment='审核意见'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_report_id'), 'approvals', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_report_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_reports_tenant_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_financial_reports_year'), table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_tenant_id'), table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_period'), table_name='financial_reports')
    op.drop_table('financial_reports')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
